Repository Infineon/infineon-vue-datatable, pull requests merged in 2022-10, with the labels that each got.

#13 12 replace dropdown for field select by something better looking
  .eslintrc.cjs
  .gitignore
  examples/src/components/examples/ExampleHideColumns.vue
  lib/datatable/InfineonDatatableShowColumnsPicker.vue
  lib/index.js
  lib/plugins/treeView/index.js
  lib/plugins/treeView/src/components/Control.vue
  lib/plugins/treeView/src/components/HiddenFields.vue
  lib/plugins/treeView/src/components/Input.vue
  lib/plugins/treeView/src/components/Menu.vue
  lib/plugins/treeView/src/components/MenuPortal.vue
  lib/plugins/treeView/src/components/MultiValue.vue
  lib/plugins/treeView/src/components/MultiValueItem.vue
  lib/plugins/treeView/src/components/Option.vue
  lib/plugins/treeView/src/components/Placeholder.vue
  lib/plugins/treeView/src/components/SingleValue.vue
  lib/plugins/treeView/src/components/Tip.vue
  lib/plugins/treeView/src/components/Treeselect.vue
  lib/plugins/treeView/src/components/icons/Arrow.vue
  lib/plugins/treeView/src/components/icons/Delete.vue
  lib/plugins/treeView/src/constants.js
  lib/plugins/treeView/src/mixins/treeselectMixin.js
  lib/plugins/treeView/src/utils/.eslintrc.js
  lib/plugins/treeView/src/utils/constant.js
  lib/plugins/treeView/src/utils/createMap.js
  lib/plugins/treeView/src/utils/debounce.js
  lib/plugins/treeView/src/utils/deepExtend.js
  lib/plugins/treeView/src/utils/find.js
  lib/plugins/treeView/src/utils/identity.js
  lib/plugins/treeView/src/utils/includes.js
  lib/plugins/treeView/src/utils/index.js
  lib/plugins/treeView/src/utils/isNaN.js
  lib/plugins/treeView/src/utils/isPromise.js
  lib/plugins/treeView/src/utils/last.js
  lib/plugins/treeView/src/utils/noop.js
  lib/plugins/treeView/src/utils/onLeftClick.js
  lib/plugins/treeView/src/utils/once.js
  lib/plugins/treeView/src/utils/quickDiff.js
  lib/plugins/treeView/src/utils/removeFromArray.js
  lib/plugins/treeView/src/utils/scrollIntoView.js
  lib/plugins/treeView/src/utils/setupResizeAndScrollEventListeners.js
  lib/plugins/treeView/src/utils/warning.js
  lib/plugins/treeView/src/utils/watchSize.js
  lib/plugins/treeView/styles/assets/checkbox-checked-disabled.png
  lib/plugins/treeView/styles/assets/checkbox-checked-disabled@2x.png
  lib/plugins/treeView/styles/assets/checkbox-checked-disabled@3x.png
  lib/plugins/treeView/styles/assets/checkbox-checked.png
  lib/plugins/treeView/styles/assets/checkbox-checked@2x.png
  lib/plugins/treeView/styles/assets/checkbox-checked@3x.png
  lib/plugins/treeView/styles/assets/checkbox-indeterminate-disabled.png
  lib/plugins/treeView/styles/assets/checkbox-indeterminate-disabled@2x.png
  lib/plugins/treeView/styles/assets/checkbox-indeterminate-disabled@3x.png
  lib/plugins/treeView/styles/assets/checkbox-indeterminate.png
  lib/plugins/treeView/styles/assets/checkbox-indeterminate@2x.png
  lib/plugins/treeView/styles/assets/checkbox-indeterminate@3x.png
  lib/plugins/treeView/styles/style.less
  package-lock.json
  package.json
Labels: minor, release

#16 15 calculation of the column length
  .gitignore
  .vscode/settings.json
  examples/src/components/examples/ExampleConditionallyHideColumns.vue
  examples/src/components/examples/ExampleStoreHiddenColumnsPerView.vue
  examples/src/components/global/TheHeader.vue
  examples/src/router/router.js
  lib/datatable/InfineonDatatable.vue
  lib/datatable/InfineonDatatableRow.vue
  package.json
Labels: patch

#17 Store hidden cols per view feature added to datatable, Example added …
  .vscode/settings.json
  examples/src/components/examples/ExampleStoreHiddenColumnsPerView.vue
  examples/src/components/global/TheHeader.vue
  examples/src/router/router.js
  lib/datatable/InfineonDatatable.vue
Labels: minor

#23 modified vue-treeselect class only for the showColumns treeselect com…
  lib/datatable/InfineonDatatableShowColumnsPicker.vue
Labels: minor
